In [1]:
import pandas as pd
import numpy as np
import pylab as pl

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

from sklearn import neighbors, tree, naive_bayes, svm, neural_network
from sklearn.svm import SVC

In [2]:
dataset = pd.read_csv("mono_feat.csv")
dataset.head()
data = dataset.iloc[:, 0:827].values
normalized_data=(data-data.mean())/data.std()
target = dataset.iloc[:,827].values

In [3]:
X_train, X_test, y_train, y_test = train_test_split(normalized_data, target, test_size=0.30)

In [4]:
knn = neighbors.KNeighborsClassifier(n_neighbors = 1)
knn.fit(X_train, y_train)
print(knn.score(X_test, y_test))
y_predic_knn = knn.predict(X_test)
confusion_matrix(y_test, y_predic_knn)

0.6933333333333334


array([[26,  0,  1,  1,  0,  0,  2,  1,  1,  0],
       [ 1, 20,  0,  1,  3,  0,  0,  1,  0,  0],
       [ 1,  1, 17,  5,  1,  0,  2,  0,  0,  8],
       [ 7,  1,  2, 17,  2,  0,  2,  1,  0,  0],
       [ 0,  4,  1,  1, 20,  0,  1,  0,  0,  3],
       [ 1,  0,  0,  0,  0, 29,  0,  0,  0,  0],
       [ 4,  0,  0,  5,  0,  0, 24,  0,  0,  0],
       [ 4,  0,  0,  0,  0,  0,  0, 24,  0,  0],
       [ 2,  0,  0,  0,  0,  0,  3,  0, 21,  0],
       [ 2,  1,  7,  5,  0,  0,  2,  0,  1, 10]], dtype=int64)

In [5]:
c45 = tree.DecisionTreeClassifier()
c45.fit(X_train, y_train)
print(c45.score(X_test, y_test))
y_predic_c45 = c45.predict(X_test)
confusion_matrix(y_test, y_predic_c45)

0.69


array([[22,  1,  0,  2,  0,  0,  2,  3,  0,  2],
       [ 4, 14,  1,  1,  4,  0,  0,  0,  1,  1],
       [ 1,  4, 20,  3,  1,  0,  0,  1,  1,  4],
       [ 5,  4,  2, 12,  2,  1,  1,  2,  1,  2],
       [ 0,  1,  0,  0, 27,  0,  0,  0,  0,  2],
       [ 2,  2,  0,  0,  0, 26,  0,  0,  0,  0],
       [ 2,  0,  1,  2,  0,  0, 25,  0,  3,  0],
       [ 0,  0,  0,  0,  0,  2,  0, 26,  0,  0],
       [ 1,  0,  0,  3,  0,  0,  0,  0, 21,  1],
       [ 4,  0,  3,  1,  0,  0,  5,  0,  1, 14]], dtype=int64)

In [6]:
gnb = naive_bayes.GaussianNB()
gnb.fit(X_train, y_train)
print(gnb.score(X_test, y_test))
y_predic_gnb = gnb.predict(X_test)
confusion_matrix(y_test, y_predic_gnb)

0.7433333333333333


array([[25,  2,  1,  0,  0,  0,  0,  0,  3,  1],
       [ 6, 16,  0,  0,  2,  0,  1,  1,  0,  0],
       [ 0,  0, 25,  4,  0,  0,  2,  0,  1,  3],
       [ 8,  5,  3, 10,  1,  0,  2,  1,  2,  0],
       [ 0,  5,  0,  0, 24,  0,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0, 28,  2,  0,  0,  0],
       [ 2,  2,  0,  2,  0,  0, 27,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 28,  0,  0],
       [ 2,  0,  0,  0,  1,  0,  0,  0, 23,  0],
       [ 3,  0,  4,  2,  2,  0,  0,  0,  0, 17]], dtype=int64)

In [7]:
svm = svm.SVC(kernel = 'poly', C = 1000,gamma = 'auto')
svm.fit(X_train, y_train) 
print(svm.score(X_test, y_test))
y_predic_svm = svm.predict(X_test)
confusion_matrix(y_test, y_predic_svm)

0.85


array([[30,  0,  1,  0,  0,  0,  0,  0,  0,  1],
       [ 0, 25,  0,  0,  1,  0,  0,  0,  0,  0],
       [ 1,  0, 27,  4,  1,  0,  0,  0,  0,  2],
       [ 4,  1,  2, 22,  2,  0,  1,  0,  0,  0],
       [ 0,  0,  0,  0, 30,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0, 29,  0,  0,  0,  0],
       [ 3,  0,  1,  1,  0,  0, 26,  0,  0,  2],
       [ 1,  1,  0,  0,  0,  0,  0, 26,  0,  0],
       [ 2,  0,  2,  0,  0,  0,  2,  0, 20,  0],
       [ 1,  0,  6,  1,  0,  0,  0,  0,  0, 20]], dtype=int64)

In [8]:
mlp = neural_network.MLPClassifier(max_iter = 4000)
mlp.fit(X_train, y_train)
print(mlp.score(X_test, y_test))
y_predic_mlp = mlp.predict(X_test)
confusion_matrix(y_test, y_predic_mlp)

0.8566666666666667


array([[28,  0,  1,  0,  0,  0,  0,  0,  0,  3],
       [ 0, 23,  1,  0,  1,  0,  1,  0,  0,  0],
       [ 1,  0, 23,  4,  0,  0,  2,  0,  0,  5],
       [ 4,  0,  2, 25,  0,  0,  0,  0,  0,  1],
       [ 0,  1,  0,  1, 28,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0, 29,  0,  0,  0,  0],
       [ 3,  0,  1,  0,  0,  0, 27,  0,  0,  2],
       [ 1,  0,  0,  0,  0,  0,  0, 27,  0,  0],
       [ 2,  0,  0,  0,  0,  0,  1,  0, 23,  0],
       [ 0,  0,  4,  0,  0,  0,  0,  0,  0, 24]], dtype=int64)